"""Generic behavior distillation helpers for torch locomotion policies."""

from .checkpoint import load_distillation_checkpoint, save_distillation_checkpoint
from .collector import (
    collect_distillation_dataset_from_env,
    collect_transition_distillation_dataset_from_env,
    command_active_mask,
    project_student_obs,
    project_teacher_obs,
)
from .dagger import (
    IterativeDaggerRunResult,
    resolve_command_intent_rollout_policies,
    run_iterative_dagger_updates,
)
from .data import (
    DistillationTensorDataset,
    annotate_distillation_dataset_scenario,
    build_distillation_dataset,
    build_multitask_distillation_dataset,
    load_distillation_dataset,
    make_fake_distillation_dataset,
    save_distillation_dataset,
)
from .fada import (
    FADA_COMMAND_SCENARIOS,
    FADA_IDM_SOURCE_ROLE_IDS,
    FADA_IDM_SOURCE_ROLES,
    FADA_SCENARIO_IDS,
    FADAArchitectureConfig,
    FADAInverseDynamicsModel,
    FADAPlanner,
    FADAPlannerIDMPolicy,
    FADASourceBatch,
    PlannerIDMOutput,
    first_action_mse,
    idm_source_loss,
    planner_source_loss,
)
from .fada_adaptation import (
    FADAAdaptationStats,
    FADAAdaptationTrainer,
    FADAAdaptedPolicy,
    FADALoRAConfig,
    FADALoRALinear,
    FADATargetSplit,
    assert_fada_adaptation_parameter_ownership,
    fada_adaptation_loss,
    fada_adapter_named_parameters,
    fada_adapter_parameters,
    inject_fada_idm_lora,
    select_fada_target_rows,
    split_fada_target_batch,
)
from .fada_adaptation_checkpoint import (
    FADA_ADAPTED_CHECKPOINT_SCHEMA_VERSION,
    assert_fada_adaptation_source_checkpoint,
    load_fada_adapted_checkpoint,
    load_fada_deployable_policy_checkpoint,
    save_fada_adapted_checkpoint,
)
from .fada_async_runtime import (
    FADA_ASYNC_SCENARIO,
    allocate_fada_command_scenarios,
    build_persistent_fada_runtime,
)
from .fada_checkpoint import (
    FADA_CHECKPOINT_SCHEMA_VERSION,
    FADA_TRAINING_SCHEDULE,
    LoadedFADAPlannerIDMPolicy,
    load_fada_checkpoint,
    load_fada_policy_checkpoint,
    save_fada_checkpoint,
)
from .fada_collector import (
    FADACollectionResult,
    FADACollectionSpec,
    collect_fada_source_windows,
)
from .fada_observation import (
    FADA_G1_ACTION_DIM,
    FADA_G1_ACTOR_OBS_DIM,
    FADA_G1_COMMAND_DIM,
    FADA_G1_STATE_DIM,
    FADA_G1_STATE_OBSERVATION_CONTRACT,
    FADA_LEGACY_OBSERVATION_CONTRACT,
    assert_fada_active_route_contract,
    assert_fada_projection_matches_contract,
    project_fada_g1_state,
    project_fada_observation_tensor,
    projection_for_fada_observation_contract,
    raw_observation_dim_for_fada_contract,
)
from .fada_oracle import load_fada_oracle_policy
from .fada_replay import FADAReplayBuffer
from .fada_source_artifact import (
    FADA_SOURCE_BATCH_SCHEMA_VERSION,
    LoadedFADASourceBatch,
    load_fada_source_batch,
    save_fada_source_batch,
)
from .fada_source_evaluation import evaluate_fada_source_batch
from .fada_source_plan import (
    FADA_INTERMEDIATE_ORACLE_COUNT,
    FADAPaperSourcePlan,
    build_fada_paper_source_plan,
)
from .fada_target_collector import (
    FADATargetCollectionResult,
    FADATargetCollectionSpec,
    collect_fada_target_windows,
)
from .fada_target_data import (
    FADA_TARGET_ARTIFACT_SCHEMA_VERSION,
    FADATargetBatch,
    LoadedFADATargetArtifact,
    load_fada_target_artifact,
    save_fada_target_artifact,
)
from .fada_trainer import FADATrainer, FADATrainingStats
from .models import MLPStudentPolicy
from .moe_diagnostics import (
    MoEExpertDiagnostics,
    MoERoleRouteSummary,
    diagnose_moe_expert_routes,
    moe_diagnostics_to_dict,
)
from .moe_student import MoEStudentOutput, MoEStudentPolicy
from .offline import (
    OfflineDistillationRunResult,
    required_balanced_replay_updates,
    required_balanced_replay_updates_for_labels,
    run_offline_distillation_updates,
)
from .performance import (
    CLEANUP_STAGE_NAMES,
    COLLECTOR_REQUEST_STAGE_NAMES,
    DISTILLATION_METRICS_SCHEMA_VERSION,
    LEGACY_REQUEST_STAGE_NAMES,
    WORKFLOW_ITERATION_STAGE_NAMES,
    DistillationPerformanceRunContext,
    DistillationStageObservation,
)
from .playback import LoadedDistillationStudentPolicy, load_distillation_student_policy
from .teacher import (
    DistillationTeacherCheckpointInfo,
    DistillationTeacherSpec,
    LoadedTeacherPolicy,
    inspect_sac_teacher_checkpoint,
    load_sac_teacher_policy,
    validate_sac_teacher_checkpoint_contract,
)
from .trainer import (
    BehaviorDistillationStats,
    BehaviorDistillationTrainer,
    DistillationBatch,
)
from .workflow import (
    ArtifactDecision,
    BootstrapWorkflowResult,
    DaggerWorkflowResult,
    RoleArtifactManifest,
    RoleArtifactPreflight,
    RoleArtifactSpec,
    WalkToStopRolePair,
    WorkflowDatasetSource,
    WorkflowScenarioCollectionResult,
    WorkflowScenarioSpec,
    WorkflowStudentUpdateResult,
    adopt_legacy_role_artifact,
    config_fingerprint,
    create_role_artifact_manifest,
    file_sha256,
    finalize_workflow_performance,
    fork_workflow_run,
    preflight_role_artifact,
    preflight_role_artifacts,
    resolve_walk_to_stop_role_pair,
    run_bootstrap_workflow,
    run_multirole_dagger_workflow,
    write_role_artifact_manifest,
)

__all__ = [
    "ArtifactDecision",
    "BootstrapWorkflowResult",
    "DaggerWorkflowResult",
    "BehaviorDistillationStats",
    "BehaviorDistillationTrainer",
    "DistillationBatch",
    "DistillationTeacherSpec",
    "DistillationPerformanceRunContext",
    "DistillationStageObservation",
    "DISTILLATION_METRICS_SCHEMA_VERSION",
    "COLLECTOR_REQUEST_STAGE_NAMES",
    "CLEANUP_STAGE_NAMES",
    "LEGACY_REQUEST_STAGE_NAMES",
    "WORKFLOW_ITERATION_STAGE_NAMES",
    "RoleArtifactManifest",
    "RoleArtifactPreflight",
    "RoleArtifactSpec",
    "WalkToStopRolePair",
    "WorkflowDatasetSource",
    "WorkflowScenarioCollectionResult",
    "WorkflowScenarioSpec",
    "WorkflowStudentUpdateResult",
    "adopt_legacy_role_artifact",
    "DistillationTeacherCheckpointInfo",
    "DistillationTensorDataset",
    "FADAAdaptedPolicy",
    "FADAAdaptationStats",
    "FADAAdaptationTrainer",
    "FADAArchitectureConfig",
    "FADA_G1_ACTION_DIM",
    "FADA_G1_ACTOR_OBS_DIM",
    "FADA_G1_COMMAND_DIM",
    "FADA_G1_STATE_DIM",
    "FADA_G1_STATE_OBSERVATION_CONTRACT",
    "FADA_LEGACY_OBSERVATION_CONTRACT",
    "FADA_ADAPTED_CHECKPOINT_SCHEMA_VERSION",
    "assert_fada_adaptation_source_checkpoint",
    "FADA_COMMAND_SCENARIOS",
    "FADACollectionResult",
    "FADATargetCollectionResult",
    "FADATargetCollectionSpec",
    "FADATargetBatch",
    "FADATargetSplit",
    "FADA_TARGET_ARTIFACT_SCHEMA_VERSION",
    "FADA_ASYNC_SCENARIO",
    "FADA_CHECKPOINT_SCHEMA_VERSION",
    "FADA_SOURCE_BATCH_SCHEMA_VERSION",
    "FADAInverseDynamicsModel",
    "FADALoRAConfig",
    "FADALoRALinear",
    "FADAPlanner",
    "FADAPlannerIDMPolicy",
    "FADASourceBatch",
    "FADA_SCENARIO_IDS",
    "FADA_IDM_SOURCE_ROLES",
    "FADA_IDM_SOURCE_ROLE_IDS",
    "FADAReplayBuffer",
    "FADATrainer",
    "FADATrainingStats",
    "FADA_TRAINING_SCHEDULE",
    "evaluate_fada_source_batch",
    "LoadedFADAPlannerIDMPolicy",
    "LoadedFADASourceBatch",
    "LoadedFADATargetArtifact",
    "annotate_distillation_dataset_scenario",
    "assert_fada_active_route_contract",
    "assert_fada_adaptation_parameter_ownership",
    "assert_fada_projection_matches_contract",
    "IterativeDaggerRunResult",
    "LoadedTeacherPolicy",
    "LoadedDistillationStudentPolicy",
    "MLPStudentPolicy",
    "MoEExpertDiagnostics",
    "MoERoleRouteSummary",
    "MoEStudentOutput",
    "MoEStudentPolicy",
    "PlannerIDMOutput",
    "OfflineDistillationRunResult",
    "build_distillation_dataset",
    "build_multitask_distillation_dataset",
    "allocate_fada_command_scenarios",
    "collect_distillation_dataset_from_env",
    "collect_fada_source_windows",
    "collect_fada_target_windows",
    "collect_transition_distillation_dataset_from_env",
    "config_fingerprint",
    "create_role_artifact_manifest",
    "command_active_mask",
    "diagnose_moe_expert_routes",
    "file_sha256",
    "fada_adapter_named_parameters",
    "fada_adapter_parameters",
    "fada_adaptation_loss",
    "first_action_mse",
    "finalize_workflow_performance",
    "fork_workflow_run",
    "inspect_sac_teacher_checkpoint",
    "inject_fada_idm_lora",
    "idm_source_loss",
    "load_distillation_checkpoint",
    "load_fada_checkpoint",
    "load_fada_adapted_checkpoint",
    "load_fada_deployable_policy_checkpoint",
    "load_fada_policy_checkpoint",
    "load_fada_oracle_policy",
    "load_fada_source_batch",
    "load_fada_target_artifact",
    "load_distillation_dataset",
    "load_distillation_student_policy",
    "load_sac_teacher_policy",
    "make_fake_distillation_dataset",
    "moe_diagnostics_to_dict",
    "project_student_obs",
    "project_fada_observation_tensor",
    "project_fada_g1_state",
    "project_teacher_obs",
    "projection_for_fada_observation_contract",
    "raw_observation_dim_for_fada_contract",
    "required_balanced_replay_updates",
    "required_balanced_replay_updates_for_labels",
    "resolve_command_intent_rollout_policies",
    "resolve_walk_to_stop_role_pair",
    "preflight_role_artifact",
    "preflight_role_artifacts",
    "planner_source_loss",
    "run_offline_distillation_updates",
    "run_iterative_dagger_updates",
    "run_bootstrap_workflow",
    "run_multirole_dagger_workflow",
    "save_distillation_checkpoint",
    "save_fada_checkpoint",
    "save_fada_adapted_checkpoint",
    "save_fada_source_batch",
    "save_fada_target_artifact",
    "select_fada_target_rows",
    "split_fada_target_batch",
    "build_persistent_fada_runtime",
    "save_distillation_dataset",
    "validate_sac_teacher_checkpoint_contract",
    "write_role_artifact_manifest",
]
