"""Generic behavior distillation helpers for torch locomotion policies."""

from .checkpoint import load_distillation_checkpoint, save_distillation_checkpoint
from .collector import (
    collect_distillation_dataset_from_env,
    collect_transition_distillation_dataset_from_env,
    command_active_mask,
    project_student_obs,
    project_teacher_obs,
)
from .dagger import (
    IterativeDaggerRunResult,
    resolve_command_intent_rollout_policies,
    run_iterative_dagger_updates,
)
from .data import (
    DistillationTensorDataset,
    annotate_distillation_dataset_scenario,
    build_distillation_dataset,
    build_multitask_distillation_dataset,
    load_distillation_dataset,
    make_fake_distillation_dataset,
    save_distillation_dataset,
)
from .models import MLPStudentPolicy
from .moe_diagnostics import (
    MoEExpertDiagnostics,
    MoERoleRouteSummary,
    diagnose_moe_expert_routes,
    moe_diagnostics_to_dict,
)
from .moe_student import MoEStudentOutput, MoEStudentPolicy
from .offline import (
    OfflineDistillationRunResult,
    required_balanced_replay_updates,
    required_balanced_replay_updates_for_labels,
    run_offline_distillation_updates,
)
from .performance import (
    CLEANUP_STAGE_NAMES,
    COLLECTOR_REQUEST_STAGE_NAMES,
    DISTILLATION_METRICS_SCHEMA_VERSION,
    LEGACY_REQUEST_STAGE_NAMES,
    WORKFLOW_ITERATION_STAGE_NAMES,
    DistillationPerformanceRunContext,
    DistillationStageObservation,
)
from .playback import LoadedDistillationStudentPolicy, load_distillation_student_policy
from .teacher import (
    DistillationTeacherCheckpointInfo,
    DistillationTeacherSpec,
    LoadedTeacherPolicy,
    inspect_sac_teacher_checkpoint,
    load_sac_teacher_policy,
    validate_sac_teacher_checkpoint_contract,
)
from .trainer import (
    BehaviorDistillationStats,
    BehaviorDistillationTrainer,
    DistillationBatch,
)
from .workflow import (
    ArtifactDecision,
    BootstrapWorkflowResult,
    DaggerWorkflowResult,
    RoleArtifactManifest,
    RoleArtifactPreflight,
    RoleArtifactSpec,
    WorkflowDatasetSource,
    WorkflowScenarioCollectionResult,
    WorkflowScenarioSpec,
    WorkflowStudentUpdateResult,
    adopt_legacy_role_artifact,
    config_fingerprint,
    create_role_artifact_manifest,
    file_sha256,
    finalize_workflow_performance,
    fork_workflow_run,
    preflight_role_artifact,
    preflight_role_artifacts,
    run_bootstrap_workflow,
    run_multirole_dagger_workflow,
    write_role_artifact_manifest,
)

__all__ = [
    "ArtifactDecision",
    "BootstrapWorkflowResult",
    "DaggerWorkflowResult",
    "BehaviorDistillationStats",
    "BehaviorDistillationTrainer",
    "DistillationBatch",
    "DistillationTeacherSpec",
    "DistillationPerformanceRunContext",
    "DistillationStageObservation",
    "DISTILLATION_METRICS_SCHEMA_VERSION",
    "COLLECTOR_REQUEST_STAGE_NAMES",
    "CLEANUP_STAGE_NAMES",
    "LEGACY_REQUEST_STAGE_NAMES",
    "WORKFLOW_ITERATION_STAGE_NAMES",
    "RoleArtifactManifest",
    "RoleArtifactPreflight",
    "RoleArtifactSpec",
    "WorkflowDatasetSource",
    "WorkflowScenarioCollectionResult",
    "WorkflowScenarioSpec",
    "WorkflowStudentUpdateResult",
    "adopt_legacy_role_artifact",
    "DistillationTeacherCheckpointInfo",
    "DistillationTensorDataset",
    "annotate_distillation_dataset_scenario",
    "IterativeDaggerRunResult",
    "LoadedTeacherPolicy",
    "LoadedDistillationStudentPolicy",
    "MLPStudentPolicy",
    "MoEExpertDiagnostics",
    "MoERoleRouteSummary",
    "MoEStudentOutput",
    "MoEStudentPolicy",
    "OfflineDistillationRunResult",
    "build_distillation_dataset",
    "build_multitask_distillation_dataset",
    "collect_distillation_dataset_from_env",
    "collect_transition_distillation_dataset_from_env",
    "config_fingerprint",
    "create_role_artifact_manifest",
    "command_active_mask",
    "diagnose_moe_expert_routes",
    "file_sha256",
    "finalize_workflow_performance",
    "fork_workflow_run",
    "inspect_sac_teacher_checkpoint",
    "load_distillation_checkpoint",
    "load_distillation_dataset",
    "load_distillation_student_policy",
    "load_sac_teacher_policy",
    "make_fake_distillation_dataset",
    "moe_diagnostics_to_dict",
    "project_student_obs",
    "project_teacher_obs",
    "required_balanced_replay_updates",
    "required_balanced_replay_updates_for_labels",
    "resolve_command_intent_rollout_policies",
    "preflight_role_artifact",
    "preflight_role_artifacts",
    "run_offline_distillation_updates",
    "run_iterative_dagger_updates",
    "run_bootstrap_workflow",
    "run_multirole_dagger_workflow",
    "save_distillation_checkpoint",
    "save_distillation_dataset",
    "validate_sac_teacher_checkpoint_contract",
    "write_role_artifact_manifest",
]
